apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nodeapp

images:
- name: nodeapp
  newName: blgianini/nodeapp
  newTag: 008dfdf89805547556bb31ccb44df9ceda74e933
